name: Build this Docker image
on:
  workflow_dispatch:
  push:
    branches: master
  schedule:
    - cron: '11 23 * * 0'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push latest
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: jugendpresse/apache:latest

      - name: Build and push 7
        id: docker_build_7
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: jugendpresse/apache:php7
          build-args: |
            VERSION=7-apache
